#!/bin/sh
#PBS -q normal
#PBS -N NGBW-JOB-RAXMLHPC2_TGB-FC2C66E7433F4722B05A18A9DD81A132
#PBS -l walltime=00:4320:00
#PBS -l epilogue=/projects/ps-ngbt/backend/trestles_workspace/NGBW-JOB-RAXMLHPC2_TGB-FC2C66E7433F4722B05A18A9DD81A132/epilogue.sh
#PBS -o scheduler_stdout.txt
#PBS -e scheduler_stderr.txt
#PBS -W umask=0007
##PBS -V

#PBS -v QOS=2

#PBS -M  terri@sdsc.edu,mmiller@sdsc.edu
#PBS -m ae
#PBS -A TG-DEB090011

#PBS -l nodes=2:ppn=32
cd /projects/ps-ngbt/backend/trestles_workspace/NGBW-JOB-RAXMLHPC2_TGB-FC2C66E7433F4722B05A18A9DD81A132

source /etc/profile.d/modules.sh

SDSC-gateway-submit-attributes $PBS_JOBID $(sed -n '/^email=/ {s/email=//; p;}' _JOBINFO.TXT)

date +'%s %a %b %e %R:%S %Z %Y' > start.txt

curl -k https://www.phylo.org/portal2/taskupdate.action?taskId=513776\&jh=NGBW-JOB-RAXMLHPC2_TGB-FC2C66E7433F4722B05A18A9DD81A132\&status=START

export CIPRES_THREADSPP=6
export CIPRES_NP=10

./batch_command.cmdline 1>stdout.txt 2>stderr.txt
retval=$?

date +'%s %a %b %e %R:%S %Z %Y' > done.txt
qstat -f $PBS_JOBID | grep Job
qstat -f $PBS_JOBID | grep resources
curl -k https://www.phylo.org/portal2/taskupdate.action?taskId=513776\&jh=NGBW-JOB-RAXMLHPC2_TGB-FC2C66E7433F4722B05A18A9DD81A132\&status=DONE
exit $retval